<?php echo $this->doctype() ?>
<html>
<head>
    
<title><?php echo $this->escape($this->title); ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link href="/wretch/public/css/site.css" rel="stylesheet" type="text/css">
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,700,400italic' rel='stylesheet' type='text/css'>

<?php echo $this->headLink(); ?>

<?php echo $this->jQuery(); ?>

<?php echo $this->headScript(); ?>

</head>

<body>

<div id="container" class="shadowbox">

<div id="logo" align="center"><a href="/">Schaver.com</a></div>

<div id="content">

<?php  echo  $this->layout()->content; ?>

</div><!-- content -->

<div align="center" id="email"><a href="mailto:mark.schaver@gmail.com">Questions or suggestions</a></div>

</div> <!-- container -->

</body>

</html>
